[project]
name = "hexlet-code"
version = "0.1.0"
description = "Website Analyzer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "ruff>=0.12.7",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.1.1",
    "black>=25.1.0",
]

